// 레벨 테스트 문항 풀 — 25문항 (difficulty 1~5 각 5문항).
// TOEIC 수준 자체 작성, vocab/grammar/listening(텍스트 기반) 혼합.
//
// ⚠️ 콘텐츠 human review 필요 — 영어 자연스러움·정답·해설을 원어민/검수자가 확인할 것.
// 정답(answer)은 반드시 options 안에 존재해야 한다.

import type { LevelTestQuestion } from '@ted-voca/shared';

export const LEVEL_TEST_QUESTIONS: LevelTestQuestion[] = [
  // ── difficulty 1 (5문항) ─────────────────────────────
  {
    id: 'lt-d1-01',
    module: 'vocab',
    difficulty: 1,
    tags: ['daily-vocab'],
    prompt: '다음 단어의 뜻은?',
    sentence: 'office',
    options: ['사무실', '공장', '학교', '병원'],
    answer: '사무실',
    explanation: 'office는 "사무실"이에요. 회사에서 일하는 공간을 가리켜.',
  },
  {
    id: 'lt-d1-02',
    module: 'vocab',
    difficulty: 1,
    tags: ['daily-vocab'],
    prompt: '빈칸에 들어갈 단어는?',
    sentence: 'I _____ to work by bus every morning.',
    options: ['go', 'goes', 'going', 'gone'],
    answer: 'go',
    explanation: '주어 I에는 동사 원형 go가 맞아. "나는 매일 아침 버스로 출근해."',
  },
  {
    id: 'lt-d1-03',
    module: 'grammar',
    difficulty: 1,
    tags: ['grammar-articles'],
    prompt: '빈칸에 알맞은 관사는?',
    sentence: 'She bought _____ apple at the store.',
    options: ['an', 'a', 'the', 'no'],
    answer: 'an',
    explanation: '모음 소리로 시작하는 apple 앞에는 an을 써. "그녀는 가게에서 사과를 샀어."',
  },
  {
    id: 'lt-d1-04',
    module: 'vocab',
    difficulty: 1,
    tags: ['daily-vocab'],
    prompt: '다음 단어의 뜻은?',
    sentence: 'meeting',
    options: ['회의', '식사', '휴가', '월급'],
    answer: '회의',
    explanation: 'meeting은 "회의"야. 비즈니스에서 정말 자주 나오는 단어.',
  },
  {
    id: 'lt-d1-05',
    module: 'listening',
    difficulty: 1,
    tags: ['listening-liaison'],
    prompt: '다음 문장을 읽고, 화자가 묻는 것은?',
    sentence: '"What time does the store open?"',
    options: ['가게가 여는 시간', '가게의 위치', '가게의 이름', '가게의 가격'],
    answer: '가게가 여는 시간',
    explanation: 'What time ~ open?은 "몇 시에 여나요?"라고 시간을 묻는 표현이야.',
  },

  // ── difficulty 2 (5문항) ─────────────────────────────
  {
    id: 'lt-d2-01',
    module: 'vocab',
    difficulty: 2,
    tags: ['business-vocab'],
    prompt: '다음 단어의 뜻은?',
    sentence: 'customer',
    options: ['고객', '직원', '관리자', '경쟁사'],
    answer: '고객',
    explanation: 'customer는 "고객"이야. client와 비슷하지만 더 일반적으로 쓰여.',
  },
  {
    id: 'lt-d2-02',
    module: 'grammar',
    difficulty: 2,
    tags: ['tense'],
    prompt: '빈칸에 알맞은 동사 형태는?',
    sentence: 'They _____ a new project last week.',
    options: ['started', 'start', 'starts', 'starting'],
    answer: 'started',
    explanation: 'last week(지난주)는 과거 시점이라 과거형 started가 맞아.',
  },
  {
    id: 'lt-d2-03',
    module: 'vocab',
    difficulty: 2,
    tags: ['business-vocab'],
    prompt: '빈칸에 들어갈 단어는?',
    sentence: 'Please _____ the report by Friday.',
    options: ['submit', 'subtract', 'subscribe', 'suggest'],
    answer: 'submit',
    explanation: 'submit the report는 "보고서를 제출하다"야. 비슷하게 생긴 단어와 혼동 주의!',
  },
  {
    id: 'lt-d2-04',
    module: 'grammar',
    difficulty: 2,
    tags: ['grammar-prepositions'],
    prompt: '빈칸에 알맞은 전치사는?',
    sentence: 'The meeting is scheduled _____ 3 p.m.',
    options: ['at', 'in', 'on', 'to'],
    answer: 'at',
    explanation: '특정 "시각" 앞에는 at을 써. at 3 p.m. = 오후 3시에.',
  },
  {
    id: 'lt-d2-05',
    module: 'listening',
    difficulty: 2,
    tags: ['listening-liaison'],
    prompt: '다음 문장을 읽고, 알맞은 응답은?',
    sentence: '"Could you send me the file?"',
    options: ['Sure, right away.', 'It is raining.', 'I am from Korea.', 'That is a cat.'],
    answer: 'Sure, right away.',
    explanation: '"파일 좀 보내줄래?"라는 요청에는 "물론, 바로 보낼게"가 자연스러운 응답이야.',
  },

  // ── difficulty 3 (5문항) ─────────────────────────────
  {
    id: 'lt-d3-01',
    module: 'vocab',
    difficulty: 3,
    tags: ['business-vocab'],
    prompt: '다음 단어의 뜻은?',
    sentence: 'invoice',
    options: ['송장', '영수증', '계약서', '견적서'],
    answer: '송장',
    explanation: 'invoice는 거래 물품과 금액을 적어 보내는 "송장"이야. receipt(영수증)와 달라.',
  },
  {
    id: 'lt-d3-02',
    module: 'grammar',
    difficulty: 3,
    tags: ['tense'],
    prompt: '빈칸에 알맞은 동사 형태는?',
    sentence: 'I have _____ here since 2020.',
    options: ['worked', 'work', 'working', 'works'],
    answer: 'worked',
    explanation: 'have + 과거분사는 현재완료. since 2020과 함께 "2020년부터 일해왔다"를 표현해.',
  },
  {
    id: 'lt-d3-03',
    module: 'vocab',
    difficulty: 3,
    tags: ['business-vocab'],
    prompt: '빈칸에 들어갈 단어는?',
    sentence: 'The company decided to _____ its operations to Asia.',
    options: ['expand', 'expense', 'expire', 'explain'],
    answer: 'expand',
    explanation: 'expand operations는 "사업을 확장하다"야. expense(비용)·expire(만료되다)와 헷갈리지 마.',
  },
  {
    id: 'lt-d3-04',
    module: 'grammar',
    difficulty: 3,
    tags: ['grammar-articles'],
    prompt: '빈칸에 알맞은 표현은?',
    sentence: 'She is _____ honest employee in the team.',
    options: ['the most', 'most', 'more', 'much'],
    answer: 'the most',
    explanation: '최상급은 the most + 형용사. "팀에서 가장 정직한 직원이야."',
  },
  {
    id: 'lt-d3-05',
    module: 'listening',
    difficulty: 3,
    tags: ['listening-liaison'],
    prompt: '다음 문장을 읽고, 화자의 의도는?',
    sentence: '"I am afraid the flight has been delayed."',
    options: ['항공편이 지연됨을 알림', '항공편이 취소됨을 알림', '항공편을 예약함', '항공편을 추천함'],
    answer: '항공편이 지연됨을 알림',
    explanation: 'has been delayed는 "지연되었다". "I am afraid ~"는 안 좋은 소식을 정중히 전하는 표현이야.',
  },

  // ── difficulty 4 (5문항) ─────────────────────────────
  {
    id: 'lt-d4-01',
    module: 'vocab',
    difficulty: 4,
    tags: ['business-vocab'],
    prompt: '다음 단어의 뜻은?',
    sentence: 'comply',
    options: ['준수하다', '불평하다', '완성하다', '구성하다'],
    answer: '준수하다',
    explanation: 'comply (with)는 규정을 "준수하다"야. complain(불평하다)과 발음이 비슷해 혼동 주의!',
  },
  {
    id: 'lt-d4-02',
    module: 'grammar',
    difficulty: 4,
    tags: ['tense'],
    prompt: '빈칸에 알맞은 동사 형태는?',
    sentence: 'By next year, the firm _____ its headquarters.',
    options: ['will have relocated', 'relocates', 'has relocated', 'relocating'],
    answer: 'will have relocated',
    explanation: 'By next year + 미래완료(will have p.p.). "내년이면 본사를 이전했을 것이다."',
  },
  {
    id: 'lt-d4-03',
    module: 'vocab',
    difficulty: 4,
    tags: ['business-vocab'],
    prompt: '빈칸에 들어갈 단어는?',
    sentence: 'Both parties agreed to _____ the terms of the contract.',
    options: ['negotiate', 'navigate', 'notify', 'nominate'],
    answer: 'negotiate',
    explanation: 'negotiate the terms는 "조건을 협상하다"야. navigate·notify와 헷갈리지 마.',
  },
  {
    id: 'lt-d4-04',
    module: 'grammar',
    difficulty: 4,
    tags: ['grammar-conditionals'],
    prompt: '빈칸에 알맞은 표현은?',
    sentence: 'If we _____ earlier, we would have caught the train.',
    options: ['had left', 'left', 'have left', 'leave'],
    answer: 'had left',
    explanation: '가정법 과거완료: If + had p.p., would have p.p. "더 일찍 떠났더라면 기차를 탔을 텐데."',
  },
  {
    id: 'lt-d4-05',
    module: 'listening',
    difficulty: 4,
    tags: ['listening-liaison'],
    prompt: '다음 문장을 읽고, 가장 자연스러운 응답은?',
    sentence: '"Would you mind if I opened the window?"',
    options: ['Not at all, go ahead.', 'Yes, I would mind it.', 'I opened it yesterday.', 'The window is blue.'],
    answer: 'Not at all, go ahead.',
    explanation: '"Would you mind ~?"에 허락할 때는 "Not at all"(전혀요)로 답해. mind = 꺼리다라서 부정이 곧 허락이야.',
  },

  // ── difficulty 5 (5문항) ─────────────────────────────
  {
    id: 'lt-d5-01',
    module: 'vocab',
    difficulty: 5,
    tags: ['business-vocab'],
    prompt: '다음 단어의 뜻은?',
    sentence: 'contingency',
    options: ['만일의 사태', '연속성', '효율성', '경쟁력'],
    answer: '만일의 사태',
    explanation: 'contingency는 예상치 못한 "만일의 사태"야. a contingency plan = 비상 대책.',
  },
  {
    id: 'lt-d5-02',
    module: 'grammar',
    difficulty: 5,
    tags: ['grammar-subjunctive'],
    prompt: '빈칸에 알맞은 동사 형태는?',
    sentence: 'The board recommended that the proposal _____ reviewed immediately.',
    options: ['be', 'is', 'was', 'will be'],
    answer: 'be',
    explanation: 'recommend that 뒤의 가정법 현재는 동사원형 be를 써. "제안서를 즉시 검토할 것을 권고했다."',
  },
  {
    id: 'lt-d5-03',
    module: 'vocab',
    difficulty: 5,
    tags: ['business-vocab'],
    prompt: '빈칸에 들어갈 단어는?',
    sentence: 'The new regulation will _____ a significant impact on small businesses.',
    options: ['have', 'take', 'make', 'do'],
    answer: 'have',
    explanation: 'have an impact on은 "~에 영향을 미치다"라는 고정 표현이야. take/make와 어울리지 않아.',
  },
  {
    id: 'lt-d5-04',
    module: 'grammar',
    difficulty: 5,
    tags: ['grammar-relative'],
    prompt: '빈칸에 알맞은 표현은?',
    sentence: 'The candidate _____ qualifications impressed us was hired.',
    options: ['whose', 'who', 'which', 'whom'],
    answer: 'whose',
    explanation: '소유 관계의 관계대명사는 whose. "그의 자격 요건이 우리를 감동시킨 지원자가 채용되었다."',
  },
  {
    id: 'lt-d5-05',
    module: 'listening',
    difficulty: 5,
    tags: ['listening-liaison'],
    prompt: '다음 문장을 읽고, 화자가 함축하는 의미는?',
    sentence: '"I would have attended the seminar, had I known about it."',
    options: ['세미나를 몰라서 참석하지 못했다', '세미나에 참석했다', '세미나를 추천한다', '세미나를 취소했다'],
    answer: '세미나를 몰라서 참석하지 못했다',
    explanation: '"had I known"은 도치된 가정법 과거완료. 몰랐기 때문에 결국 참석하지 못했다는 뜻이야.',
  },
];
