#!/usr/bin/env python3
"""Generate words seed SQL (002_words_seed.sql) from the TOEIC 800 word pack JSON.

Reads content/toeic-800-pack.json and emits an idempotent INSERT migration that
resolves course_id via a subquery on courses.slug = 'toeic-800'.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INPUT = ROOT / "content" / "toeic-800-pack.json"
OUTPUT = ROOT / "supabase" / "migrations" / "002_words_seed.sql"
SCRIPT_REL = "scripts/generate_words_seed_sql.py"

COURSE_SLUG = "toeic-800"

# Allowed word_pos enum values (see 001_initial_schema.sql)
VALID_POS = {
    "noun",
    "verb",
    "adjective",
    "adverb",
    "preposition",
    "conjunction",
    "other",
}


def sql_str(value) -> str:
    """Render a Python value as a SQL literal, escaping single quotes.

    None / empty-after-strip -> NULL.
    """
    if value is None:
        return "NULL"
    text = str(value)
    if text == "":
        return "NULL"
    escaped = text.replace("'", "''")
    return f"'{escaped}'"


def sql_array(values) -> str:
    """Render a list of strings as a PostgreSQL TEXT[] array literal."""
    if not values:
        return "ARRAY[]::TEXT[]"
    items = ", ".join(sql_str(v) for v in values)
    return f"ARRAY[{items}]"


def map_pos(pos: str) -> str:
    pos = (pos or "").strip()
    return pos if pos in VALID_POS else "other"


def build_row(word: dict) -> str:
    course_id = f"(SELECT id FROM courses WHERE slug = '{COURSE_SLUG}')"
    lemma = sql_str(word.get("lemma"))
    pos = sql_str(map_pos(word.get("pos")))
    meaning_ko = sql_str(word.get("meaning_ko"))
    meaning_en = "NULL"  # not present in source JSON
    example_en = sql_str(word.get("example_en"))
    # empty example_ko -> NULL
    example_ko_raw = word.get("example_ko")
    example_ko = sql_str(example_ko_raw if example_ko_raw else None)
    phonetic = "NULL"  # not present in source JSON
    tags = sql_array(word.get("tags") or [])
    difficulty = int(word.get("difficulty", 1))
    sort_order = int(word.get("sort_order", 0))

    cols = [
        course_id,
        lemma,
        pos,
        meaning_ko,
        meaning_en,
        example_en,
        example_ko,
        phonetic,
        tags,
        str(difficulty),
        str(sort_order),
    ]
    return "  (" + ", ".join(cols) + ")"


def main() -> None:
    data = json.loads(INPUT.read_text(encoding="utf-8"))
    words = data["words"]

    rows = [build_row(w) for w in words]

    header = (
        "-- Ted Voca — Words Seed (toeic-800)\n"
        f"-- Generated by: {SCRIPT_REL}\n"
        f"-- Source: content/toeic-800-pack.json\n"
        f"-- Word count: {len(words)}\n"
        "-- Idempotent: re-runnable via ON CONFLICT (course_id, lemma) DO NOTHING\n"
        "-- Apply: supabase db push OR run in Supabase SQL Editor\n\n"
    )

    insert = (
        "INSERT INTO words "
        "(course_id, lemma, pos, meaning_ko, meaning_en, example_en, "
        "example_ko, phonetic, tags, difficulty, sort_order)\nVALUES\n"
        + ",\n".join(rows)
        + "\nON CONFLICT (course_id, lemma) DO NOTHING;\n"
    )

    update = (
        "\n-- Sync course word_count\n"
        "UPDATE courses\n"
        f"SET word_count = (SELECT COUNT(*) FROM words w "
        f"WHERE w.course_id = courses.id)\n"
        f"WHERE slug = '{COURSE_SLUG}';\n"
    )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(header + insert + update, encoding="utf-8")

    print(f"Wrote {len(rows)} word rows to {OUTPUT}")


if __name__ == "__main__":
    main()
