-- Ted Voca — Listening Seed (clips + questions)
-- Generated by: scripts/generate_listening_seed.py
-- Source: scripts/listening_content/batch_*.txt
-- Clip count: 30  Question count: 50
-- Idempotent: ON CONFLICT (slug) / (clip_id, sort_order) DO NOTHING
-- Apply: supabase db push OR run in Supabase SQL Editor

-- Schema fixes for listening content (idempotent).
-- Requires PostgreSQL 12+ (ALTER TYPE ... ADD VALUE in transaction — Supabase Cloud OK)
-- 리스닝 attempt는 quiz_type='listening'으로 기록 (remote.recordListeningAttempt)
-- 주의: ALTER TYPE ... ADD VALUE는 같은 트랜잭션 안에서 새 enum 값을 사용할 수 없으나,
--   본 시드는 새 값을 사용하지 않으므로(quiz_type 컬럼에 'listening' INSERT 없음) 단일 실행 OK.
ALTER TYPE quiz_type ADD VALUE IF NOT EXISTS 'listening';

-- listening_clips 확장 컬럼
ALTER TABLE listening_clips ADD COLUMN IF NOT EXISTS slug TEXT;
ALTER TABLE listening_clips ADD COLUMN IF NOT EXISTS audio_url TEXT;       -- v1.1 예약
ALTER TABLE listening_clips ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';
ALTER TABLE listening_clips ADD COLUMN IF NOT EXISTS sort_order INT DEFAULT 0;

-- slug NOT NULL 보장: NULL slug 행(001 시절 데이터)이 UNIQUE를 우회하지 않도록
-- 기존 행은 id 텍스트로 백필 후 제약 적용 (재실행 안전).
UPDATE listening_clips SET slug = id::text WHERE slug IS NULL;
ALTER TABLE listening_clips ALTER COLUMN slug SET NOT NULL;

-- UNIQUE(slug): ADD CONSTRAINT IF NOT EXISTS는 PG 미지원 → DO 블록.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'listening_clips_slug_unique'
  ) THEN
    ALTER TABLE listening_clips
      ADD CONSTRAINT listening_clips_slug_unique UNIQUE (slug);
  END IF;
END $$;

-- listening_questions 신설
CREATE TABLE IF NOT EXISTS listening_questions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  clip_id UUID REFERENCES listening_clips(id) ON DELETE CASCADE,
  prompt TEXT NOT NULL,
  options JSONB NOT NULL,            -- {"choices": [...]}
  correct_answer TEXT NOT NULL,
  explanation TEXT,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- UNIQUE(clip_id, sort_order): DO 블록.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'listening_questions_clip_sort_unique'
  ) THEN
    ALTER TABLE listening_questions
      ADD CONSTRAINT listening_questions_clip_sort_unique
      UNIQUE (clip_id, sort_order);
  END IF;
END $$;

-- RLS: 누구나(authenticated) 읽기 가능. CREATE POLICY IF NOT EXISTS 미지원 → DROP 후 CREATE.
ALTER TABLE listening_questions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS listening_questions_read_all ON listening_questions;
CREATE POLICY listening_questions_read_all
  ON listening_questions FOR SELECT TO authenticated USING (TRUE);

-- quiz_attempts에 listening_question_id 추가
ALTER TABLE quiz_attempts
  ADD COLUMN IF NOT EXISTS listening_question_id UUID
  REFERENCES listening_questions(id) ON DELETE SET NULL;

-- Clips
INSERT INTO listening_clips (slug, title, transcript_en, transcript_ko, duration_seconds, difficulty, tags, sort_order)
VALUES
  ('airport-boarding', '탑승 안내방송', 'Attention passengers on flight 207 to Tokyo. Boarding will begin in ten minutes at gate B12.', '도쿄행 207편 승객 여러분께 안내드립니다. 탑승은 10분 후 B12 게이트에서 시작됩니다.', 6, 2, ARRAY['announcement', 'travel', 'airport']::TEXT[], 1),
  ('airport-delay', '항공편 지연 안내', 'We are sorry to announce that flight 88 to London has been delayed by one hour due to bad weather.', '런던행 88편이 악천후로 1시간 지연되었음을 알려드려 죄송합니다.', 8, 3, ARRAY['announcement', 'travel', 'airport']::TEXT[], 2),
  ('airport-baggage', '수하물 찾는 곳 안내', 'Passengers arriving from Sydney can collect their baggage at carousel number five.', '시드니에서 도착하신 승객 여러분은 5번 수하물 컨베이어에서 짐을 찾으실 수 있습니다.', 5, 2, ARRAY['announcement', 'travel', 'airport']::TEXT[], 3),
  ('airport-final-call', '최종 탑승 안내', 'This is the final call for passenger Kim traveling to Paris. Please proceed to gate A7 immediately.', '파리로 가시는 승객 Kim님께 마지막 안내입니다. 즉시 A7 게이트로 와 주시기 바랍니다.', 7, 3, ARRAY['announcement', 'travel', 'airport']::TEXT[], 4),
  ('station-train-delay', '열차 지연 안내', 'The express train to Busan is running about fifteen minutes late. We apologize for the inconvenience.', '부산행 급행열차가 약 15분 지연되고 있습니다. 불편을 드려 죄송합니다.', 6, 2, ARRAY['announcement', 'travel', 'station']::TEXT[], 5),
  ('station-platform-change', '승강장 변경 안내', 'The train to Incheon will now depart from platform three instead of platform one.', '인천행 열차가 1번 승강장 대신 3번 승강장에서 출발합니다.', 6, 3, ARRAY['announcement', 'travel', 'station']::TEXT[], 6),
  ('station-last-train', '막차 안내방송', 'The last train tonight leaves at eleven thirty. Please make sure you are on the platform before that time.', '오늘 밤 막차는 11시 30분에 출발합니다. 그 전에 승강장에 도착해 주시기 바랍니다.', 8, 2, ARRAY['announcement', 'travel', 'station']::TEXT[], 7),
  ('subway-doors', '지하철 출입문 안내', 'Please stand clear of the closing doors. The next stop is City Hall.', '닫히는 문에서 물러서 주십시오. 다음 역은 시청역입니다.', 5, 1, ARRAY['announcement', 'travel', 'station']::TEXT[], 8),
  ('inflight-seatbelt', '기내 좌석벨트 안내', 'Ladies and gentlemen, we are about to land. Please fasten your seatbelt and return your seat to the upright position.', '승객 여러분, 곧 착륙하겠습니다. 좌석벨트를 매시고 좌석 등받이를 세워 주시기 바랍니다.', 8, 3, ARRAY['announcement', 'travel', 'airport']::TEXT[], 9),
  ('inflight-meal', '기내식 안내', 'We will now begin our meal service. Today we are offering chicken with rice or pasta.', '지금부터 기내식 서비스를 시작하겠습니다. 오늘은 닭고기 덮밥 또는 파스타를 제공합니다.', 6, 2, ARRAY['announcement', 'travel', 'airport']::TEXT[], 10),
  ('office-meeting-time', '사내 회의 공지', 'The weekly team meeting has been moved to Thursday at three in the conference room on the fifth floor.', '주간 팀 회의가 목요일 오후 3시 5층 회의실로 변경되었습니다.', 8, 2, ARRAY['office', 'announcement', 'meeting']::TEXT[], 11),
  ('office-printer', '프린터 점검 공지', 'The printer on the third floor will be out of service this afternoon for maintenance. Please use the one on the second floor.', '3층 프린터가 오늘 오후 점검으로 사용이 중단됩니다. 2층 프린터를 이용해 주십시오.', 9, 2, ARRAY['office', 'announcement']::TEXT[], 12),
  ('office-deadline', '보고서 마감 공지', 'This is a reminder that the monthly sales report is due by Friday noon. Please send it to your manager.', '월간 영업 보고서 마감이 금요일 정오임을 다시 알려드립니다. 담당 매니저에게 보내 주세요.', 8, 3, ARRAY['office', 'announcement']::TEXT[], 13),
  ('office-parking', '주차장 안내 공지', 'Starting next Monday, the company parking lot will be closed for repairs. Employees can park in the public garage nearby.', '다음 주 월요일부터 회사 주차장이 수리를 위해 폐쇄됩니다. 직원들은 인근 공용 주차장을 이용할 수 있습니다.', 8, 2, ARRAY['office', 'announcement']::TEXT[], 14),
  ('office-fire-drill', '소방 훈련 공지', 'We will hold a fire drill tomorrow at ten in the morning. When you hear the alarm, please leave the building calmly using the stairs.', '내일 오전 10시에 소방 훈련을 실시합니다. 경보가 울리면 계단을 이용해 침착하게 건물 밖으로 나가 주십시오.', 10, 3, ARRAY['office', 'announcement']::TEXT[], 15),
  ('phone-message-doctor', '병원 예약 음성 메시지', 'Hi, this is a reminder from Green Clinic. Your appointment with Doctor Lee is tomorrow at two thirty. Please call us if you cannot come.', '안녕하세요, 그린 클리닉에서 알려드립니다. 이 선생님과의 예약이 내일 2시 30분입니다. 오실 수 없으면 전화 주세요.', 10, 2, ARRAY['daily', 'phone']::TEXT[], 16),
  ('phone-message-delivery', '택배 배송 음성 메시지', 'Hello, this is City Delivery. We tried to deliver your package today but no one was home. We will try again tomorrow morning.', '안녕하세요, 시티 딜리버리입니다. 오늘 배송을 시도했으나 댁에 아무도 안 계셨습니다. 내일 오전에 다시 시도하겠습니다.', 9, 2, ARRAY['daily', 'phone']::TEXT[], 17),
  ('phone-message-restaurant', '식당 예약 확인 메시지', 'Hi, this is Bella Restaurant calling to confirm your table for four people this Saturday at seven in the evening.', '안녕하세요, 벨라 레스토랑입니다. 이번 주 토요일 저녁 7시 4인석 예약을 확인하려고 전화드립니다.', 8, 3, ARRAY['daily', 'phone']::TEXT[], 18),
  ('weather-rain', '오늘의 날씨 예보', 'Good morning. Today will be cloudy with heavy rain in the afternoon. Don''t forget to take an umbrella with you.', '좋은 아침입니다. 오늘은 흐리고 오후에 강한 비가 내리겠습니다. 우산을 잊지 말고 챙기세요.', 8, 2, ARRAY['daily', 'weather']::TEXT[], 19),
  ('weather-cold', '한파 주의 예보', 'Tonight will be very cold, with temperatures dropping below zero. Please wear warm clothes if you go outside.', '오늘 밤은 기온이 영하로 떨어져 매우 춥겠습니다. 외출하실 때는 따뜻한 옷을 입으세요.', 7, 3, ARRAY['daily', 'weather']::TEXT[], 20),
  ('weather-weekend', '주말 날씨 안내', 'The weekend forecast looks great. Saturday will be sunny and warm, perfect for outdoor activities.', '주말 예보가 아주 좋습니다. 토요일은 맑고 따뜻해 야외 활동에 안성맞춤이겠습니다.', 6, 2, ARRAY['daily', 'weather']::TEXT[], 21),
  ('shopping-sale', '매장 세일 안내방송', 'Attention shoppers. For the next hour, all winter coats are thirty percent off on the second floor.', '고객 여러분께 안내드립니다. 앞으로 한 시간 동안 2층의 모든 겨울 코트를 30% 할인합니다.', 7, 2, ARRAY['daily', 'announcement']::TEXT[], 22),
  ('shopping-closing', '매장 마감 안내', 'Our store will be closing in fifteen minutes. Please bring your items to the checkout counter.', '저희 매장은 15분 후 마감합니다. 구매하실 물건을 계산대로 가져와 주십시오.', 6, 1, ARRAY['daily', 'announcement']::TEXT[], 23),
  ('shopping-lost-child', '미아 안내방송', 'We have a young boy named Sam waiting at the customer service desk. Could his parents please come to collect him?', '고객 서비스 데스크에서 Sam이라는 남자아이가 기다리고 있습니다. 부모님께서는 데리러 와 주시기 바랍니다.', 8, 3, ARRAY['daily', 'announcement']::TEXT[], 24),
  ('library-hours', '도서관 운영 안내', 'Welcome to the city library. Please note that we close early today at six in the evening for a special event.', '시립 도서관에 오신 것을 환영합니다. 오늘은 특별 행사로 저녁 6시에 일찍 마감하는 점 참고해 주세요.', 8, 2, ARRAY['daily', 'announcement']::TEXT[], 25),
  ('cafe-order', '카페 주문 안내', 'Your order is ready. One large coffee and one chocolate muffin. Please pick it up at the counter.', '주문하신 음료가 준비되었습니다. 라지 사이즈 커피 한 잔과 초콜릿 머핀 하나입니다. 카운터에서 받아 가세요.', 7, 1, ARRAY['daily']::TEXT[], 26),
  ('gym-class', '헬스장 수업 안내', 'The morning yoga class will start in ten minutes in studio two. Please bring your own mat.', '아침 요가 수업이 10분 후 2번 스튜디오에서 시작됩니다. 개인 매트를 가져와 주세요.', 7, 2, ARRAY['daily', 'announcement']::TEXT[], 27),
  ('hotel-checkout', '호텔 체크아웃 안내', 'Good morning. Please remember that checkout time is eleven o''clock. If you need a late checkout, contact the front desk.', '좋은 아침입니다. 체크아웃 시간은 11시임을 기억해 주세요. 레이트 체크아웃이 필요하시면 프런트로 연락 주세요.', 8, 3, ARRAY['daily', 'travel']::TEXT[], 28),
  ('bus-route-change', '버스 노선 변경 안내', 'Due to road work, bus number twelve will not stop at Oak Street today. The nearest stop will be Pine Avenue.', '도로 공사로 인해 오늘 12번 버스는 오크 스트리트에 정차하지 않습니다. 가장 가까운 정류장은 파인 애비뉴입니다.', 8, 3, ARRAY['daily', 'travel', 'announcement']::TEXT[], 29),
  ('museum-tour', '박물관 투어 안내', 'A free guided tour of the art gallery will begin at two o''clock near the main entrance. Everyone is welcome.', '미술관 무료 가이드 투어가 2시에 정문 근처에서 시작됩니다. 누구나 환영합니다.', 8, 2, ARRAY['daily', 'announcement']::TEXT[], 30)
ON CONFLICT (slug) DO NOTHING;

-- Questions
INSERT INTO listening_questions (clip_id, prompt, options, correct_answer, explanation, sort_order)
VALUES
  ((SELECT id FROM listening_clips WHERE slug = 'airport-boarding'), 'Where will the flight depart from?', '{"choices": ["Gate B2", "Gate B12", "Gate B20"]}'::JSONB, 'Gate B12', '안내방송에서 ''at gate B12''라고 출발 게이트를 명시했습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'airport-boarding'), 'When does boarding begin?', '{"choices": ["In ten minutes", "In two minutes", "Right now"]}'::JSONB, 'In ten minutes', '''Boarding will begin in ten minutes''에서 10분 후 시작한다고 했습니다.', 2),
  ((SELECT id FROM listening_clips WHERE slug = 'airport-delay'), 'Why is the flight delayed?', '{"choices": ["Bad weather", "A technical problem", "A crew shortage"]}'::JSONB, 'Bad weather', '''due to bad weather''에서 지연 사유가 악천후임을 알 수 있습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'airport-delay'), 'How long is the delay?', '{"choices": ["Thirty minutes", "One hour", "Two hours"]}'::JSONB, 'One hour', '''delayed by one hour''에서 지연 시간이 1시간임을 확인할 수 있습니다.', 2),
  ((SELECT id FROM listening_clips WHERE slug = 'airport-baggage'), 'Where can passengers collect their baggage?', '{"choices": ["Carousel five", "Carousel nine", "The information desk"]}'::JSONB, 'Carousel five', '''at carousel number five''에서 5번 컨베이어라고 안내했습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'airport-final-call'), 'What should passenger Kim do?', '{"choices": ["Go to gate A7", "Check in luggage", "Wait at the cafe"]}'::JSONB, 'Go to gate A7', '''proceed to gate A7 immediately''에서 즉시 A7 게이트로 가야 함을 알 수 있습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'station-train-delay'), 'How late is the train?', '{"choices": ["About five minutes", "About fifteen minutes", "About fifty minutes"]}'::JSONB, 'About fifteen minutes', '''about fifteen minutes late''에서 약 15분 지연임을 알 수 있습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'station-train-delay'), 'Where is the train going?', '{"choices": ["Busan", "Seoul", "Daegu"]}'::JSONB, 'Busan', '''The express train to Busan''에서 목적지가 부산입니다.', 2),
  ((SELECT id FROM listening_clips WHERE slug = 'station-platform-change'), 'Which platform will the train now use?', '{"choices": ["Platform one", "Platform three", "Platform two"]}'::JSONB, 'Platform three', '''depart from platform three instead of platform one''에서 변경된 승강장은 3번입니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'station-last-train'), 'What time does the last train leave?', '{"choices": ["At eleven thirty", "At ten thirty", "At twelve thirty"]}'::JSONB, 'At eleven thirty', '''leaves at eleven thirty''에서 막차 시간이 11시 30분입니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'subway-doors'), 'What is the next stop?', '{"choices": ["Central Park", "City Hall", "Main Street"]}'::JSONB, 'City Hall', '''The next stop is City Hall''에서 다음 역이 시청역입니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'inflight-seatbelt'), 'What are passengers asked to do?', '{"choices": ["Fasten their seatbelt", "Open the window", "Use their phone"]}'::JSONB, 'Fasten their seatbelt', '''Please fasten your seatbelt''에서 좌석벨트를 매라고 요청했습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'inflight-seatbelt'), 'What is about to happen?', '{"choices": ["The plane will land", "The plane will take off", "Meals will be served"]}'::JSONB, 'The plane will land', '''we are about to land''에서 곧 착륙함을 알 수 있습니다.', 2),
  ((SELECT id FROM listening_clips WHERE slug = 'inflight-meal'), 'What meal options are offered?', '{"choices": ["Chicken or pasta", "Beef or fish", "Salad or soup"]}'::JSONB, 'Chicken or pasta', '''chicken with rice or pasta''에서 선택지가 닭고기와 파스타임을 알 수 있습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'office-meeting-time'), 'When is the meeting now?', '{"choices": ["Thursday at three", "Wednesday at three", "Thursday at five"]}'::JSONB, 'Thursday at three', '''moved to Thursday at three''에서 변경된 시각이 목요일 3시입니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'office-meeting-time'), 'Where will the meeting take place?', '{"choices": ["The fifth floor conference room", "The cafeteria", "The first floor lobby"]}'::JSONB, 'The fifth floor conference room', '''conference room on the fifth floor''에서 장소가 5층 회의실입니다.', 2),
  ((SELECT id FROM listening_clips WHERE slug = 'office-printer'), 'Why is the printer out of service?', '{"choices": ["For maintenance", "It is broken", "It is being replaced"]}'::JSONB, 'For maintenance', '''out of service this afternoon for maintenance''에서 점검 때문임을 알 수 있습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'office-deadline'), 'When is the report due?', '{"choices": ["By Friday noon", "By Monday noon", "By Friday evening"]}'::JSONB, 'By Friday noon', '''due by Friday noon''에서 마감이 금요일 정오임을 알 수 있습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'office-deadline'), 'Who should receive the report?', '{"choices": ["The manager", "A client", "The receptionist"]}'::JSONB, 'The manager', '''send it to your manager''에서 매니저에게 보내라고 했습니다.', 2),
  ((SELECT id FROM listening_clips WHERE slug = 'office-parking'), 'When will the parking lot close?', '{"choices": ["Next Monday", "This Friday", "Next month"]}'::JSONB, 'Next Monday', '''Starting next Monday''에서 다음 주 월요일부터 폐쇄됨을 알 수 있습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'office-fire-drill'), 'What should employees do when they hear the alarm?', '{"choices": ["Leave using the stairs", "Take the elevator", "Stay at their desks"]}'::JSONB, 'Leave using the stairs', '''leave the building calmly using the stairs''에서 계단으로 대피하라고 했습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'office-fire-drill'), 'When is the fire drill?', '{"choices": ["Tomorrow at ten", "Today at ten", "Tomorrow at two"]}'::JSONB, 'Tomorrow at ten', '''tomorrow at ten in the morning''에서 내일 오전 10시입니다.', 2),
  ((SELECT id FROM listening_clips WHERE slug = 'phone-message-doctor'), 'When is the appointment?', '{"choices": ["Tomorrow at two thirty", "Today at two thirty", "Tomorrow at three thirty"]}'::JSONB, 'Tomorrow at two thirty', '''tomorrow at two thirty''에서 예약이 내일 2시 30분입니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'phone-message-doctor'), 'What should the listener do if they cannot come?', '{"choices": ["Call the clinic", "Send an email", "Visit another doctor"]}'::JSONB, 'Call the clinic', '''Please call us if you cannot come''에서 못 오면 전화하라고 했습니다.', 2),
  ((SELECT id FROM listening_clips WHERE slug = 'phone-message-delivery'), 'Why was the package not delivered?', '{"choices": ["No one was home", "The address was wrong", "It was too heavy"]}'::JSONB, 'No one was home', '''no one was home''에서 집에 아무도 없어 배송하지 못했음을 알 수 있습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'phone-message-delivery'), 'When will they try again?', '{"choices": ["Tomorrow morning", "This evening", "Next week"]}'::JSONB, 'Tomorrow morning', '''try again tomorrow morning''에서 내일 오전에 다시 시도합니다.', 2),
  ((SELECT id FROM listening_clips WHERE slug = 'phone-message-restaurant'), 'How many people is the reservation for?', '{"choices": ["Four", "Two", "Seven"]}'::JSONB, 'Four', '''table for four people''에서 4인석 예약임을 알 수 있습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'phone-message-restaurant'), 'When is the reservation?', '{"choices": ["Saturday at seven", "Sunday at seven", "Saturday at five"]}'::JSONB, 'Saturday at seven', '''this Saturday at seven in the evening''에서 토요일 저녁 7시입니다.', 2),
  ((SELECT id FROM listening_clips WHERE slug = 'weather-rain'), 'What will the weather be like in the afternoon?', '{"choices": ["Heavy rain", "Sunny", "Snowy"]}'::JSONB, 'Heavy rain', '''heavy rain in the afternoon''에서 오후에 강한 비가 옴을 알 수 있습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'weather-rain'), 'What does the speaker suggest taking?', '{"choices": ["An umbrella", "Sunglasses", "A jacket"]}'::JSONB, 'An umbrella', '"Don''t forget to take an umbrella"에서 우산을 챙기라고 했습니다.', 2),
  ((SELECT id FROM listening_clips WHERE slug = 'weather-cold'), 'How cold will it be tonight?', '{"choices": ["Below zero", "Around twenty", "Mild and warm"]}'::JSONB, 'Below zero', '''temperatures dropping below zero''에서 영하로 떨어진다고 했습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'weather-cold'), 'What advice does the speaker give?', '{"choices": ["Wear warm clothes", "Stay home all day", "Drink cold water"]}'::JSONB, 'Wear warm clothes', '''wear warm clothes if you go outside''에서 따뜻한 옷을 입으라고 조언했습니다.', 2),
  ((SELECT id FROM listening_clips WHERE slug = 'weather-weekend'), 'What is the weather like on Saturday?', '{"choices": ["Sunny and warm", "Rainy and cold", "Windy and cloudy"]}'::JSONB, 'Sunny and warm', '''Saturday will be sunny and warm''에서 토요일이 맑고 따뜻함을 알 수 있습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'shopping-sale'), 'What items are on sale?', '{"choices": ["Winter coats", "Summer shoes", "Children''s toys"]}'::JSONB, 'Winter coats', '''all winter coats are thirty percent off''에서 겨울 코트가 할인 품목입니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'shopping-sale'), 'How much is the discount?', '{"choices": ["Thirty percent", "Thirteen percent", "Fifty percent"]}'::JSONB, 'Thirty percent', '''thirty percent off''에서 할인율이 30%임을 알 수 있습니다.', 2),
  ((SELECT id FROM listening_clips WHERE slug = 'shopping-closing'), 'When will the store close?', '{"choices": ["In fifteen minutes", "In fifty minutes", "In five minutes"]}'::JSONB, 'In fifteen minutes', '''closing in fifteen minutes''에서 15분 후 마감함을 알 수 있습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'shopping-lost-child'), 'Where is the boy waiting?', '{"choices": ["The customer service desk", "The parking lot", "The food court"]}'::JSONB, 'The customer service desk', '''waiting at the customer service desk''에서 고객 서비스 데스크에서 기다린다고 했습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'shopping-lost-child'), 'Who is asked to come?', '{"choices": ["His parents", "His teacher", "A doctor"]}'::JSONB, 'His parents', '''Could his parents please come''에서 부모님을 호출했습니다.', 2),
  ((SELECT id FROM listening_clips WHERE slug = 'library-hours'), 'Why does the library close early today?', '{"choices": ["For a special event", "For cleaning", "For a holiday"]}'::JSONB, 'For a special event', '''close early today at six ... for a special event''에서 특별 행사 때문임을 알 수 있습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'library-hours'), 'What time does the library close today?', '{"choices": ["At six", "At eight", "At four"]}'::JSONB, 'At six', '''close early today at six in the evening''에서 오늘은 저녁 6시에 마감합니다.', 2),
  ((SELECT id FROM listening_clips WHERE slug = 'cafe-order'), 'What did the customer order?', '{"choices": ["Coffee and a muffin", "Tea and a sandwich", "Juice and a cookie"]}'::JSONB, 'Coffee and a muffin', '''One large coffee and one chocolate muffin''에서 커피와 머핀을 주문했습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'cafe-order'), 'Where should the customer pick up the order?', '{"choices": ["At the counter", "At the table", "At the entrance"]}'::JSONB, 'At the counter', '''pick it up at the counter''에서 카운터에서 받으라고 했습니다.', 2),
  ((SELECT id FROM listening_clips WHERE slug = 'gym-class'), 'Where will the yoga class be held?', '{"choices": ["Studio two", "Studio one", "The pool"]}'::JSONB, 'Studio two', '''in studio two''에서 수업 장소가 2번 스튜디오입니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'gym-class'), 'What should participants bring?', '{"choices": ["Their own mat", "A water bottle", "Running shoes"]}'::JSONB, 'Their own mat', '''bring your own mat''에서 개인 매트를 가져오라고 했습니다.', 2),
  ((SELECT id FROM listening_clips WHERE slug = 'hotel-checkout'), 'What time is checkout?', '{"choices": ["Eleven o''clock", "Ten o''clock", "Twelve o''clock"]}'::JSONB, 'Eleven o''clock', '''checkout time is eleven o''''clock''에서 체크아웃이 11시임을 알 수 있습니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'hotel-checkout'), 'Who should you contact for a late checkout?', '{"choices": ["The front desk", "Room service", "The manager"]}'::JSONB, 'The front desk', '''contact the front desk''에서 프런트에 연락하라고 했습니다.', 2),
  ((SELECT id FROM listening_clips WHERE slug = 'bus-route-change'), 'Why is the bus route changed?', '{"choices": ["Road work", "A festival", "Heavy traffic"]}'::JSONB, 'Road work', '''Due to road work''에서 도로 공사가 변경 이유입니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'bus-route-change'), 'What is the nearest stop today?', '{"choices": ["Pine Avenue", "Oak Street", "Main Street"]}'::JSONB, 'Pine Avenue', '''The nearest stop will be Pine Avenue''에서 가장 가까운 정류장이 파인 애비뉴입니다.', 2),
  ((SELECT id FROM listening_clips WHERE slug = 'museum-tour'), 'When does the guided tour start?', '{"choices": ["At two o''clock", "At noon", "At three o''clock"]}'::JSONB, 'At two o''clock', '''begin at two o''''clock''에서 투어가 2시에 시작합니다.', 1),
  ((SELECT id FROM listening_clips WHERE slug = 'museum-tour'), 'Where does the tour begin?', '{"choices": ["Near the main entrance", "In the gift shop", "On the rooftop"]}'::JSONB, 'Near the main entrance', '''near the main entrance''에서 정문 근처에서 시작합니다.', 2)
ON CONFLICT (clip_id, sort_order) DO NOTHING;
