-- Ted Voca — Speaking Seed (scenarios + dialogue turns + usage/attempts schema)
-- Generated by: scripts/generate_speaking_seed.py
-- Source: scripts/speaking_content/batch_*.txt
-- Scenario count: 10  Turn count: 68
-- Idempotent: ON CONFLICT (slug) / (scenario_id, turn_order) DO NOTHING
-- Apply: supabase db push OR run in Supabase SQL Editor

-- Schema fixes for speaking content (idempotent).
-- 001에서 speaking_scenarios.slug는 이미 UNIQUE NOT NULL → 중복 DDL 없음.
-- speaking_scenarios 확장 컬럼
ALTER TABLE speaking_scenarios ADD COLUMN IF NOT EXISTS emoji TEXT DEFAULT '💬';
ALTER TABLE speaking_scenarios ADD COLUMN IF NOT EXISTS min_level INT DEFAULT 1;
ALTER TABLE speaking_scenarios ADD COLUMN IF NOT EXISTS sort_order INT DEFAULT 0;

-- dialogue_turns UNIQUE(scenario_id, turn_order): ON CONFLICT 시드 대상.
-- ADD CONSTRAINT IF NOT EXISTS 미지원 → DO 블록.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'dialogue_turns_scenario_order_unique'
  ) THEN
    ALTER TABLE dialogue_turns
      ADD CONSTRAINT dialogue_turns_scenario_order_unique
      UNIQUE (scenario_id, turn_order);
  END IF;
END $$;

-- speaking_usage: 일일 사용량(비용 cap). user_id+usage_date PK.
CREATE TABLE IF NOT EXISTS speaking_usage (
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  usage_date DATE NOT NULL,
  count INT DEFAULT 0,
  PRIMARY KEY (user_id, usage_date)
);

-- speaking_attempts: 발화 + 피드백 기록 (음성 파일 미저장 — 텍스트만).
CREATE TABLE IF NOT EXISTS speaking_attempts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  scenario_id UUID REFERENCES speaking_scenarios(id) ON DELETE SET NULL,
  turn_order INT,
  user_text TEXT NOT NULL,
  feedback JSONB,                      -- {verdict, correction, alternative}
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS: 본인 row만. usage 증가·attempt insert는 Edge Function(service role)이
-- RLS를 우회하여 수행하므로, 정책은 본인 읽기/쓰기 위주로 둔다.
ALTER TABLE speaking_usage ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS speaking_usage_select_own ON speaking_usage;
CREATE POLICY speaking_usage_select_own
  ON speaking_usage FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS speaking_usage_insert_own ON speaking_usage;
CREATE POLICY speaking_usage_insert_own
  ON speaking_usage FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS speaking_usage_update_own ON speaking_usage;
CREATE POLICY speaking_usage_update_own
  ON speaking_usage FOR UPDATE TO authenticated USING (auth.uid() = user_id);

ALTER TABLE speaking_attempts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS speaking_attempts_select_own ON speaking_attempts;
CREATE POLICY speaking_attempts_select_own
  ON speaking_attempts FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS speaking_attempts_insert_own ON speaking_attempts;
CREATE POLICY speaking_attempts_insert_own
  ON speaking_attempts FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- 일일 사용량 원자적 검사·증가 (비용 한도 우회 방지 — Edge Function이 service role로 호출).
-- UPDATE ... WHERE count < limit 가 row lock으로 동시 요청을 직렬화 → 한도 초과 시 0행 반환.
CREATE OR REPLACE FUNCTION increment_speaking_usage(p_user UUID, p_date DATE, p_limit INT)
RETURNS TABLE(allowed BOOLEAN, remaining INT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_count INT;
BEGIN
  INSERT INTO speaking_usage (user_id, usage_date, count)
  VALUES (p_user, p_date, 1)
  ON CONFLICT (user_id, usage_date)
  DO UPDATE SET count = speaking_usage.count + 1
    WHERE speaking_usage.count < p_limit
  RETURNING count INTO v_count;

  IF v_count IS NULL THEN
    -- ON CONFLICT WHERE가 막음(한도 도달) → 차단
    RETURN QUERY SELECT FALSE, 0;
  ELSE
    RETURN QUERY SELECT TRUE, GREATEST(0, p_limit - v_count);
  END IF;
END;
$$;

-- RPC는 service role만 실행 (authenticated 직접 호출 차단 — 한도 조작 방지).
REVOKE ALL ON FUNCTION increment_speaking_usage(UUID, DATE, INT) FROM PUBLIC, authenticated, anon;

-- Scenarios
INSERT INTO speaking_scenarios (slug, title, context, difficulty, emoji, min_level, sort_order)
VALUES
  ('cafe-order', '카페 주문', 'You are ordering a drink at a coffee shop. The barista greets you at the counter.', 1, '☕', 1, 1),
  ('hotel-checkin', '호텔 체크인', 'You arrive at a hotel front desk to check in for your stay.', 2, '🏨', 2, 2),
  ('restaurant-order', '식당 주문', 'You are at a restaurant and the server comes to take your order.', 2, '🍽️', 3, 3),
  ('asking-directions', '길 찾기', 'You are lost in a new city and ask a friendly local for directions to the station.', 2, '🗺️', 4, 4),
  ('shopping-clothes', '옷 쇼핑', 'You are shopping for clothes and a store assistant offers to help you.', 3, '🛍️', 5, 5),
  ('phone-appointment', '전화 예약', 'You are calling a clinic to make an appointment with the receptionist.', 3, '📞', 6, 6),
  ('airport-checkin', '공항 체크인', 'You are at the airport check-in counter for an international flight.', 3, '✈️', 7, 7),
  ('business-meeting', '비즈니스 미팅', 'You are introducing yourself at the start of a business meeting with a new partner.', 4, '💼', 9, 8),
  ('doctor-visit', '병원 진료', 'You are describing your symptoms to a doctor during a medical visit.', 4, '🏥', 10, 9),
  ('job-interview', '면접', 'You are in a job interview and the interviewer asks about your background.', 5, '🧑‍💼', 12, 10)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  context = EXCLUDED.context,
  difficulty = EXCLUDED.difficulty,
  emoji = EXCLUDED.emoji,
  min_level = EXCLUDED.min_level,
  sort_order = EXCLUDED.sort_order;

-- Dialogue turns
INSERT INTO dialogue_turns (scenario_id, turn_order, speaker, text_en, hint_ko)
VALUES
  ((SELECT id FROM speaking_scenarios WHERE slug = 'cafe-order'), 1, 'ted', 'Hi there! What can I get for you today?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'cafe-order'), 2, 'user', 'I would like a latte, please.', '라떼 한 잔 주세요.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'cafe-order'), 3, 'ted', 'Sure. What size would you like?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'cafe-order'), 4, 'user', 'A large one, please.', '큰 사이즈로 주세요.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'cafe-order'), 5, 'ted', 'Great. Anything else?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'cafe-order'), 6, 'user', 'No, that is all. Thank you.', '아니요, 그게 다예요. 감사합니다.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'cafe-order'), 7, 'ted', 'Perfect. It will be ready in a moment.', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'hotel-checkin'), 1, 'ted', 'Good evening! Welcome. Do you have a reservation?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'hotel-checkin'), 2, 'user', 'Yes, I have a reservation under the name Park.', '네, 박이라는 이름으로 예약했습니다.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'hotel-checkin'), 3, 'ted', 'Let me check. May I see your passport, please?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'hotel-checkin'), 4, 'user', 'Here it is.', '여기 있습니다.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'hotel-checkin'), 5, 'ted', 'Thank you. You are in room 502 on the fifth floor.', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'hotel-checkin'), 6, 'user', 'Could you tell me what time breakfast is served?', '아침 식사는 몇 시에 제공되나요?'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'hotel-checkin'), 7, 'ted', 'Breakfast is from seven to ten in the main restaurant.', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'restaurant-order'), 1, 'ted', 'Good evening. Are you ready to order?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'restaurant-order'), 2, 'user', 'Yes, I will have the grilled salmon, please.', '네, 구운 연어로 할게요.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'restaurant-order'), 3, 'ted', 'Excellent choice. Would you like soup or salad with that?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'restaurant-order'), 4, 'user', 'I will have the salad, please.', '샐러드로 주세요.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'restaurant-order'), 5, 'ted', 'And something to drink?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'restaurant-order'), 6, 'user', 'Just water for now, thank you.', '우선 물만 주세요, 감사합니다.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'asking-directions'), 1, 'ted', 'You look a little lost. Can I help you?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'asking-directions'), 2, 'user', 'Yes, how do I get to the train station?', '네, 기차역까지 어떻게 가나요?'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'asking-directions'), 3, 'ted', 'Go straight for two blocks, then turn left.', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'asking-directions'), 4, 'user', 'Is it far from here?', '여기서 먼가요?'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'asking-directions'), 5, 'ted', 'No, it is about a five minute walk.', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'asking-directions'), 6, 'user', 'Thank you so much for your help.', '도와주셔서 정말 감사합니다.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'asking-directions'), 7, 'ted', 'You are welcome. Have a good day!', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'shopping-clothes'), 1, 'ted', 'Hello! Are you looking for anything in particular?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'shopping-clothes'), 2, 'user', 'Yes, I am looking for a winter jacket.', '네, 겨울 재킷을 찾고 있어요.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'shopping-clothes'), 3, 'ted', 'Of course. What size do you wear?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'shopping-clothes'), 4, 'user', 'I usually wear a medium.', '보통 미디엄을 입어요.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'shopping-clothes'), 5, 'ted', 'Here is one in medium. Would you like to try it on?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'shopping-clothes'), 6, 'user', 'Yes, where is the fitting room?', '네, 탈의실이 어디인가요?'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'shopping-clothes'), 7, 'ted', 'It is right over there, on your left.', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'phone-appointment'), 1, 'ted', 'Good morning, Sunrise Clinic. How may I help you?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'phone-appointment'), 2, 'user', 'Hello, I would like to make an appointment.', '안녕하세요, 예약을 하고 싶어요.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'phone-appointment'), 3, 'ted', 'Certainly. What day works best for you?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'phone-appointment'), 4, 'user', 'Would Thursday afternoon be possible?', '목요일 오후가 가능할까요?'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'phone-appointment'), 5, 'ted', 'Yes, we have an opening at three o''clock.', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'phone-appointment'), 6, 'user', 'That works for me. Thank you.', '저는 괜찮아요. 감사합니다.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'airport-checkin'), 1, 'ted', 'Good morning. May I see your passport and ticket?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'airport-checkin'), 2, 'user', 'Sure, here you are.', '네, 여기 있습니다.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'airport-checkin'), 3, 'ted', 'Are you checking any bags today?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'airport-checkin'), 4, 'user', 'Yes, I have one suitcase to check in.', '네, 부칠 가방이 하나 있어요.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'airport-checkin'), 5, 'ted', 'Please place it on the scale. Would you like a window seat?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'airport-checkin'), 6, 'user', 'A window seat would be great, thank you.', '창가 자리면 좋겠어요, 감사합니다.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'airport-checkin'), 7, 'ted', 'All set. Your gate is 23, boarding at ten thirty.', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'business-meeting'), 1, 'ted', 'Welcome. It is a pleasure to finally meet you in person.', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'business-meeting'), 2, 'user', 'Thank you. I have been looking forward to this meeting.', '감사합니다. 이번 미팅을 기대하고 있었습니다.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'business-meeting'), 3, 'ted', 'Shall we start by reviewing the proposal?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'business-meeting'), 4, 'user', 'Yes, let us begin with the budget section.', '네, 예산 부분부터 시작하시죠.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'business-meeting'), 5, 'ted', 'Sounds good. Do you have any initial concerns?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'business-meeting'), 6, 'user', 'I would like to discuss the timeline in more detail.', '일정에 대해 좀 더 자세히 논의하고 싶습니다.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'business-meeting'), 7, 'ted', 'Of course. Let me walk you through our schedule.', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'doctor-visit'), 1, 'ted', 'Hello. What seems to be the problem today?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'doctor-visit'), 2, 'user', 'I have had a sore throat and a fever since yesterday.', '어제부터 목이 아프고 열이 나요.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'doctor-visit'), 3, 'ted', 'I see. Have you taken any medicine for it?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'doctor-visit'), 4, 'user', 'I took some painkillers, but they did not help much.', '진통제를 먹었지만 별로 효과가 없었어요.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'doctor-visit'), 5, 'ted', 'Let me examine you. Please open your mouth and say ah.', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'doctor-visit'), 6, 'user', 'How long will it take to recover?', '회복하는 데 얼마나 걸릴까요?'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'doctor-visit'), 7, 'ted', 'With rest and medication, you should feel better in a few days.', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'job-interview'), 1, 'ted', 'Thanks for coming in. Could you tell me about yourself?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'job-interview'), 2, 'user', 'I have five years of experience in marketing.', '저는 마케팅 분야에서 5년의 경력이 있습니다.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'job-interview'), 3, 'ted', 'Impressive. Why are you interested in this position?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'job-interview'), 4, 'user', 'I am drawn to your company''s focus on innovation.', '귀사의 혁신에 대한 집중에 끌렸습니다.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'job-interview'), 5, 'ted', 'What would you say is your greatest strength?', NULL),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'job-interview'), 6, 'user', 'I am very good at solving problems under pressure.', '저는 압박 속에서 문제를 해결하는 데 능숙합니다.'),
  ((SELECT id FROM speaking_scenarios WHERE slug = 'job-interview'), 7, 'ted', 'Great. Do you have any questions for us?', NULL)
ON CONFLICT (scenario_id, turn_order) DO NOTHING;
